-- Tamil Nadu Government Schemes - Demo Data
-- Categories: Women, Students, Farmers, Disabled, Health, Housing, Employment, General

-- Clean existing data to avoid PK conflicts during development
DELETE FROM eligibility_rules;
DELETE FROM schemes;

INSERT INTO schemes (id, scheme_name, description, category, active) VALUES
-- WOMEN WELFARE (1-20)
(1, 'Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme', 'Financial assistance of Rs. 1000/month for girl students from government schools pursuing higher education.', 'Women', true),
(2, 'Chief Minister’s Girl Child Protection Scheme', 'Deposits for girl children to ensure their education and prevent female infanticide.', 'Women', true),
(3, 'Dr. Muthulakshmi Reddy Maternity Benefit Scheme', 'Financial assistance of Rs. 18,000 for pregnant women to ensure nutrition and health.', 'Women', true),
(4, 'Sivagami Ammaiyar Memorial Girl Child Protection Scheme', 'Financial assistance for the marriage of poor girls.', 'Women', true),
(5, 'E.V.R. Maniammaiyar Ninaivu Marriage Assistance Scheme', 'Financial aid for daughters of poor widows.', 'Women', true),
(6, 'Annai Teresa Ninaivu Marriage Assistance Scheme', 'Financial help for orphan girls for their marriage.', 'Women', true),
(7, 'Widow Remarriage Assistance Scheme', 'Incentive for remarriage of young widows.', 'Women', true),
(8, 'Free Sewing Machine Scheme', 'Providing sewing machines to poor women to enhance self-employment.', 'Women', true),
(9, 'Working Women’s Hostel Scheme', 'Safe and affordable accommodation for working women.', 'Women', true),
(10, 'Amma Two Wheeler Scheme', 'Subsidized scooters for working women.', 'Women', true),
(11, 'Women Self Help Group (SHG) Loan Scheme', 'Low-interest loans for women SHGs to start businesses.', 'Women', true),
(12, 'Sathyavani Muthu Ammaiyar Ninaivu Free Supply of Sewing Machine', 'Sewing machines for destitute widows and deserted wives.', 'Women', true),
(13, 'Tamil Nadu Rural Livelihood Mission (TNRLM)', 'Empowering rural women through skill development and employment.', 'Women', true),
(14, 'Mahalir Thittam', 'Empowering women through SHGs and entrepreneurship training.', 'Women', true),
(15, 'Destitute Widow Pension Scheme', 'Monthly pension for destitute widows.', 'Women', true),
(16, 'Deserted Wives Pension Scheme', 'Financial support for women deserted by husbands.', 'Women', true),
(17, 'Unmarried Women Pension Scheme', 'Pension for unmarried women above 50 years.', 'Women', true),
(18, 'Inter-caste Marriage Assistance Scheme', 'Financial incentive for inter-caste marriages.', 'Women', true),
(19, 'Transgender Pension Scheme', 'Monthly pension for destitute transgenders.', 'Women', true),
(20, 'Victim Compensation Scheme', 'Financial relief for women victims of crimes.', 'Women', true),

-- STUDENTS & EDUCATION (21-50)
(21, 'Pudhumai Penn Scheme', 'Rs. 1000 monthly for girl students fromgovt schools in colleges.', 'Student', true),
(22, 'Free Laptop Scheme', 'Free laptops for higher secondary and college students.', 'Student', true),
(23, 'Free Bicycle Scheme', 'Free bicycles for class 11 students.', 'Student', true),
(24, 'Chief Minister’s Breakfast Scheme', 'Nutritious breakfast for primary school students.', 'Student', true),
(25, 'Mid-Day Meal Scheme (Puratchi Thalaivar MGR Nutritious Meal)', 'Hot cooked meals for school children.', 'Student', true),
(26, 'Post Matric Scholarship for SC/ST', 'Scholarship for SC/ST students in higher education.', 'Student', true),
(27, 'Post Matric Scholarship for BC/MBC', 'Scholarship for BC/MBC students.', 'Student', true),
(28, 'First Generation Graduate Scholarship', 'Tuition fee waiver for first graduates in a family.', 'Student', true),
(29, 'Tamil Nadu Skill Development Corporation (TNSDC) Training', 'Free skill training for unemployed youth.', 'Student', true),
(30, 'Naan Mudhalvan Scheme', 'Skill development program for college students.', 'Student', true),
(31, 'Illam Thedi Kalvi', 'Doonstep education to bridge learning gaps.', 'Student', true),
(32, 'Educational Loan Subsidy Scheme', 'Interest subsidy on educational loans.', 'Student', true),
(33, 'Periyar EVR Nagammai Scheme', 'Financial support for girl students in PG courses.', 'Student', true),
(34, 'Incentive for Full Attendance', 'Cash incentive for students with 100% attendance.', 'Student', true),
(35, 'Free Uniforms and Textbooks', 'Free study materials for govt school students.', 'Student', true),
(36, 'Special Cash Incentive for 10th/12th Toppers', 'Cash awards for district and state toppers.', 'Student', true),
(37, 'Language Lab Scheme', 'English language training for rural students.', 'Student', true),
(38, 'Free Bus Pass Scheme', 'Free travel for students to schools and colleges.', 'Student', true),
(39, 'Ph.D. Scholarship Scheme', 'Financial aid for full-time Ph.D. scholars.', 'Student', true),
(40, 'Overseas Scholarship Scheme', 'Funding for SC/ST students studying abroad.', 'Student', true),
(41, 'Maritime Education Scholarship', 'Support for students in maritime courses.', 'Student', true),
(42, 'Law Graduate Scholarship', 'Stipend for junior lawyers.', 'Student', true),
(43, 'Sports Scholarship Scheme', 'Financial aid for state-level athletes.', 'Student', true),
(44, 'Tamil Medium Stipend', 'Stipend for students studying in Tamil medium.', 'Student', true),
(45, 'Differently Abled Student Scholarship', 'Scholarship for students with disabilities.', 'Student', true),
(46, 'Hostel Subsidy', 'Food and accommodation subsidy for hostel students.', 'Student', true),
(47, 'Research Fellowship for Tamil Studies', 'Focus on ancient Tamil literature research.', 'Student', true),
(48, 'Chief Minister’s Research Fellowship', 'Fellowship for top-tier research scholars.', 'Student', true),
(49, 'Digital Literacy Program', 'Basic computer training for rural students.', 'Student', true),
(50, 'Career Guidance Cell', 'Career counseling in all government colleges.', 'Student', true),

-- FARMERS & AGRICULTURE (51-80)
(51, 'Kalaignar All Village Integrated Agricultural Development Program', 'Holistic development of agriculture in villages.', 'Farmer', true),
(52, 'Free Electricity for Farmers', 'Free power supply for agricultural pumpsets.', 'Farmer', true),
(53, 'Uzhavar Sandhai', 'Direct farmer-to-consumer markets.', 'Farmer', true),
(54, 'Kuruvai Cultivation Package', 'Subsidized inputs for Kuruvai crop season.', 'Farmer', true),
(55, 'Micro Irrigation Scheme', 'Subsidy for drip and sprinkler irrigation systems.', 'Farmer', true),
(56, 'Agricultural Mechanization Scheme', 'Subsidy for purchasing farm machinery.', 'Farmer', true),
(57, 'Crop Insurance Scheme (PMFBY)', 'Insurance coverage for crop loss.', 'Farmer', true),
(58, 'Collective Farming Scheme', 'Grouping farmers to pool resources and credit.', 'Farmer', true),
(59, 'Seed Village Scheme', 'Distribution of quality seeds at subsidized rates.', 'Farmer', true),
(60, 'Soil Health Card Scheme', 'Testing soil and recommending nutrients.', 'Farmer', true),
(61, 'Organic Farming Promotion', 'Incentives for adopting organic farming practices.', 'Farmer', true),
(62, 'Horticulture Development Mission', 'Promoting fruit and vegetable cultivation.', 'Farmer', true),
(63, 'Coconut Development Board Schemes', 'Support for coconut growers.', 'Farmer', true),
(64, 'Sugarcane Production Incentive', 'Incentives for high-yield sugarcane production.', 'Farmer', true),
(65, 'Milch Animal Distribution Scheme', 'Free cows/goats for poor rural families.', 'Farmer', true),
(66, 'Fodder Development Scheme', 'Promoting fodder cultivation for livestock.', 'Farmer', true),
(67, 'Poultry Development Scheme', 'Subsidy for backyard poultry farming.', 'Farmer', true),
(68, 'Inland Fisheries Development', 'Support for fish farming in ponds.', 'Farmer', true),
(69, 'Marine Fishermen Saving and Relief Scheme', 'Financial relief during fishing ban period.', 'Farmer', true),
(70, 'Motorization of Traditional Fishing Craft', 'Subsidy for outboard motors.', 'Farmer', true),
(71, 'Millet Mission', 'Promoting cultivation of millets.', 'Farmer', true),
(72, 'Agro-Processing Cluster Scheme', 'Infrastructure for food processing units.', 'Farmer', true),
(73, 'Rainwater Harvesting in Farms', 'Subsidy for farm ponds.', 'Farmer', true),
(74, 'Solar Powered Pumpset Scheme', 'Subsidized solar pumps for irrigation.', 'Farmer', true),
(75, 'Interest Free Crop Loan', 'Zero interest loans for cooperative societies.', 'Farmer', true),
(76, 'Farmers Grievance Redressal Day', 'Monthly meeting to solve farmer issues.', 'Farmer', true),
(77, 'Establishment of Cold Storage', 'Cold storage facilities for perishables.', 'Farmer', true),
(78, 'Paddy Procurement Scheme', 'Minimum Support Price (MSP) for paddy', 'Farmer', true),
(79, 'Fertilizer Subsidy Scheme', 'Provision of fertilizers at reduced rates.', 'Farmer', true),
(80, 'Beekeeping Promotion', 'Subsidy for setting up apiaries.', 'Farmer', true),

-- HEALTH & SOCIAL WELFARE (81-110)
(81, 'Makkalai Thedi Maruthuvam', 'Doorstep healthcare service for non-communicable diseases.', 'Health', true),
(82, 'Chief Minister’s Comprehensive Health Insurance Scheme', 'Cashless medical treatment for poor families.', 'Health', true),
(83, 'Dr. Muthulakshmi Reddy Maternity Assistance', 'Financial aid for maternity care.', 'Health', true),
(84, 'Varumun Kappom', 'Preventive health camps in rural areas.', 'Health', true),
(85, 'Innuyir Kappom - Nammai Kakkum 48', 'Free emergency care for accident victims for first 48 hours.', 'Health', true),
(86, 'Amma Baby Care Kit', 'Kit comprising baby essentials for newborns.', 'Health', true),
(87, 'Menstrual Hygiene Scheme', 'Free sanitary napkins for adolescent girls.', 'Health', true),
(88, 'School Health Programme', 'Regular health checkups for school students.', 'Health', true),
(89, 'Blindness Control Programme', 'Free cataract surgeries and eye screenings.', 'Health', true),
(90, 'Tuberculosis Control Programme', 'Free TB treatment and nutrition support.', 'Health', true),
(91, 'Leprosy Eradication Programme', 'Early detection and treatment of leprosy.', 'Health', true),
(92, 'Mental Health Programme', 'Counseling/treatment for mental health issues.', 'Health', true),
(93, 'Ayush Holistic Health Centers', 'Promoting Siddha, Ayurveda, and Yoga.', 'Health', true),
(94, 'Mobile Medical Units', 'Medical vans for remote tribal areas.', 'Health', true),
(95, 'Pradhan Mantri Matru Vandana Yojana (PMMVY)', 'Maternity benefit program (Central share).', 'Health', true),
(96, 'Poshan Abhiyan (Nutrition Mission)', 'Reducing malnutrition in children and women.', 'Health', true),
(97, 'Old Age Pension Scheme (OAP)', 'Monthly pension for senior citizens.', 'Health', true),
(98, 'Destitute Physically Handicapped Pension', 'Pension for differently-abled destitute.', 'Health', true),
(99, 'Free Bus Pass for Differently Abled', 'Travel concession for disabled persons.', 'Health', true),
(100, 'Maintenance Allowance for Mentally Retarded', 'Monthly allowance for caregivers.', 'Health', true),
(101, 'Marriage Assistance for Differently Abled', 'Incentive for marrying a differently-abled person.', 'Health', true),
(102, 'Assistive Devices Distribution', 'Free wheelchairs, hearing aids, etc.', 'Health', true),
(103, 'Special Schools for Disabled', 'Running special schools with hostel facilities.', 'Health', true),
(104, 'Homes for the Aged', 'Grant-in-aid for NGOs running old age homes.', 'Health', true),
(105, 'De-addiction Centers', 'Support for alcohol and drug de-addiction.', 'Health', true),
(106, 'Transgender Clinic', 'Specialized clinics for transgender health.', 'Health', true),
(107, 'Amma Pharmacy', 'Low-cost generic medicine shops.', 'Health', true),
(108, 'Sanitation Campaign', 'Constructing toilets in rural households.', 'Health', true),
(109, 'Palliative Care Scheme', 'Care for terminally ill patients at home.', 'Health', true),
(110, 'Health Mix Distribution', 'Nutritious flour mix for pregnant women.', 'Health', true),

-- HOUSING & EMPLOYMENT (111-140)
(111, 'Kalaignar Kanavu Illam', 'Housing for rural poor.', 'Housing', true),
(112, 'Pradhan Mantri Awas Yojana (Urban)', 'Affordable housing for urban poor.', 'Housing', true),
(113, 'Pradhan Mantri Awas Yojana (Rural)', 'Affordable housing for rural poor.', 'Housing', true),
(114, 'Green House Scheme (Pasumai Veedu)', 'Solar-powered eco-friendly houses.', 'Housing', true),
(115, 'Slum Clearance Board Tenements', 'Resettlement of slum dwellers.', 'Housing', true),
(116, 'Housing Loan for Government Employees', 'Low-interest housing loans.', 'Housing', true),
(117, 'Credit Linked Subsidy Scheme', 'Interest subsidy on home loans.', 'Housing', true),
(118, 'Samathuvapuram Scheme', 'Housing colonies promoting social harmony.', 'Housing', true),
(119, 'Rent-to-Own Scheme', 'Rental housing that can be owned later.', 'Housing', true),
(120, 'Hostel for Construction Workers', 'Accommodation for migrant laborers.', 'Housing', true),
(121, 'MGNREGS (100 Days Work)', 'Rural employment guarantee scheme.', 'Employment', true),
(122, 'Urban Employment Scheme', 'Employment guarantee in urban areas.', 'Employment', true),
(123, 'UYEGP (Unemployed Youth Employment Generation)', 'Loans for youth to start small businesses.', 'Employment', true),
(124, 'NEEDS (New Entrepreneur Enterprise Development)', 'Subsidy for first-generation entrepreneurs.', 'Employment', true),
(125, 'PMEGP (Prime Minister Employment Generation)', 'Credit-linked subsidy for micro-enterprises.', 'Employment', true),
(126, 'Mudra Loan Scheme', 'Loans for small businesses without collateral.', 'Employment', true),
(127, 'Street Vendor Support Scheme', 'Credit for street vendors (PM SVANidhi).', 'Employment', true),
(128, 'Startup TN', 'Support system for startups in Tamil Nadu.', 'Employment', true),
(129, 'Amma Call Center', 'Grievance redressal employment.', 'Employment', true),
(130, 'Job Fairs (Mega Job Mela)', 'Organizing job fairs for private sector jobs.', 'Employment', true),
(131, 'Apprenticeship Training Scheme', 'Stipend for apprentices in industries.', 'Employment', true),
(132, 'Overseas Manpower Corporation', 'Facilitating overseas employment.', 'Employment', true),
(133, 'Self-Employment for Differently Abled', 'Loans for disabled to start shops.', 'Employment', true),
(134, 'Cooperative Loans for Artisans', 'Credit for weavers and artisans.', 'Employment', true),
(135, 'Skill Training for Tribal Youth', 'Vocational training for tribal communities.', 'Employment', true),
(136, 'Single Window Portal', 'Ease of doing business for MSMEs.', 'Employment', true),
(137, 'Global Investors Meet', 'Attracting FDI for job creation.', 'Employment', true),
(138, 'Industrial Estate Allotment', 'Land for industries at subsidized rates.', 'Employment', true),
(139, 'Power Subsidy for Powerlooms', 'Subsidy for powerloom weavers.', 'Employment', true),
(140, 'Free Dhoti and Saree Scheme', 'Distribution during Pongal festival (supports weavers).', 'Employment', true),

-- MISCELLANEOUS & INFRASTRUCTURE (141-150)
(141, 'Namakku Naame Thittam', 'Community participation in infrastructure building.', 'General', true),
(142, 'Anna Marumalarchi Thittam', 'Revival of village infrastructure.', 'General', true),
(143, 'Pongal Gift Hamper', 'Cash and grocery kit for ration card holders.', 'General', true),
(144, 'Free Bus Travel for Women', 'Zero ticket cost for women in town buses.', 'Women', true),
(145, 'Chief Minister’s Relief Fund', 'Financial aid for medical/disaster relief.', 'General', true),
(146, 'Member of Legislative Assembly Constituency Development Scheme (MLACDS)', 'Local area development.', 'General', true),
(147, 'Smart City Mission', 'Urban infrastructure modernization.', 'General', true),
(148, 'Amma Amudhan Departmental Store', 'Subsidized grocery stores.', 'General', true),
(149, 'Kalaignar Nagarpura Membattu Thittam', 'Urban development scheme.', 'General', true),
(150, 'Singara Chennai 2.0', 'Beautification and infrastructure of Chennai.', 'General', true);


-- Eligibility Rules
-- NOTE: Replacing NULL with 0 for Age and 99999999 for Income to avoid NOT NULL constraints.
-- Mapped 150 rules to 150 schemes.

INSERT INTO eligibility_rules (scheme_id, min_age, max_income, category, location) VALUES
-- Women (1-20)
(1, 17, 300000, 'Women', 'Tamil Nadu'),
(2, 0, 72000, 'Women', 'Tamil Nadu'),
(3, 18, 100000, 'Women', 'Tamil Nadu'),
(4, 18, 72000, 'Women', 'Tamil Nadu'),
(5, 18, 72000, 'Women', 'Tamil Nadu'),
(6, 18, 72000, 'Women', 'Tamil Nadu'),
(7, 20, 100000, 'Women', 'Tamil Nadu'),
(8, 20, 72000, 'Women', 'Tamil Nadu'),
(9, 18, 500000, 'Women', 'Tamil Nadu'),
(10, 18, 250000, 'Women', 'Tamil Nadu'),
(11, 18, 99999999, 'Women', 'Tamil Nadu'),
(12, 20, 72000, 'Women', 'Tamil Nadu'),
(13, 18, 99999999, 'Women', 'Tamil Nadu'),
(14, 18, 99999999, 'Women', 'Tamil Nadu'),
(15, 40, 50000, 'Women', 'Tamil Nadu'),
(16, 30, 50000, 'Women', 'Tamil Nadu'),
(17, 50, 50000, 'Women', 'Tamil Nadu'),
(18, 18, 99999999, 'Women', 'Tamil Nadu'),
(19, 18, 50000, 'Women', 'Tamil Nadu'),
(20, 0, 99999999, 'Women', 'Tamil Nadu'),

-- Students (21-50)
(21, 17, 99999999, 'Student', 'Tamil Nadu'),
(22, 16, 99999999, 'Student', 'Tamil Nadu'),
(23, 15, 99999999, 'Student', 'Tamil Nadu'),
(24, 5, 99999999, 'Student', 'Tamil Nadu'),
(25, 4, 99999999, 'Student', 'Tamil Nadu'),
(26, 18, 250000, 'Student', 'Tamil Nadu'),
(27, 18, 200000, 'Student', 'Tamil Nadu'),
(28, 18, 200000, 'Student', 'Tamil Nadu'),
(29, 18, 99999999, 'Student', 'Tamil Nadu'),
(30, 18, 99999999, 'Student', 'Tamil Nadu'),
(31, 5, 99999999, 'Student', 'Tamil Nadu'),
(32, 18, 500000, 'Student', 'Tamil Nadu'),
(33, 21, 200000, 'Student', 'Tamil Nadu'),
(34, 5, 99999999, 'Student', 'Tamil Nadu'),
(35, 5, 99999999, 'Student', 'Tamil Nadu'),
(36, 15, 99999999, 'Student', 'Tamil Nadu'),
(37, 10, 99999999, 'Student', 'Tamil Nadu'),
(38, 5, 99999999, 'Student', 'Tamil Nadu'),
(39, 23, 500000, 'Student', 'Tamil Nadu'),
(40, 21, 800000, 'Student', 'Tamil Nadu'),
(41, 18, 99999999, 'Student', 'Tamil Nadu'),
(42, 22, 99999999, 'Student', 'Tamil Nadu'),
(43, 12, 99999999, 'Student', 'Tamil Nadu'),
(44, 15, 99999999, 'Student', 'Tamil Nadu'),
(45, 5, 99999999, 'Student', 'Tamil Nadu'),
(46, 15, 200000, 'Student', 'Tamil Nadu'),
(47, 21, 99999999, 'Student', 'Tamil Nadu'),
(48, 22, 99999999, 'Student', 'Tamil Nadu'),
(49, 10, 99999999, 'Student', 'Tamil Nadu'),
(50, 17, 99999999, 'Student', 'Tamil Nadu'),

-- Farmers (51-80)
(51, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(52, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(53, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(54, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(55, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(56, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(57, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(58, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(59, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(60, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(61, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(62, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(63, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(64, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(65, 18, 72000, 'Farmer', 'Tamil Nadu'),
(66, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(67, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(68, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(69, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(70, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(71, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(72, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(73, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(74, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(75, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(76, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(77, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(78, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(79, 18, 99999999, 'Farmer', 'Tamil Nadu'),
(80, 18, 99999999, 'Farmer', 'Tamil Nadu'),

-- Health (81-110)
(81, 0, 99999999, 'Health', 'Tamil Nadu'),
(82, 0, 120000, 'Health', 'Tamil Nadu'),
(83, 18, 100000, 'Health', 'Tamil Nadu'),
(84, 0, 99999999, 'Health', 'Tamil Nadu'),
(85, 0, 99999999, 'Health', 'Tamil Nadu'),
(86, 0, 99999999, 'Health', 'Tamil Nadu'),
(87, 12, 99999999, 'Health', 'Tamil Nadu'),
(88, 5, 99999999, 'Health', 'Tamil Nadu'),
(89, 50, 200000, 'Health', 'Tamil Nadu'),
(90, 0, 99999999, 'Health', 'Tamil Nadu'),
(91, 0, 99999999, 'Health', 'Tamil Nadu'),
(92, 0, 99999999, 'Health', 'Tamil Nadu'),
(93, 0, 99999999, 'Health', 'Tamil Nadu'),
(94, 0, 99999999, 'Health', 'Tamil Nadu'),
(95, 18, 99999999, 'Health', 'Tamil Nadu'),
(96, 0, 99999999, 'Health', 'Tamil Nadu'),
(97, 60, 50000, 'Health', 'Tamil Nadu'),
(98, 0, 50000, 'Health', 'Tamil Nadu'),
(99, 0, 99999999, 'Health', 'Tamil Nadu'),
(100, 0, 100000, 'Health', 'Tamil Nadu'),
(101, 18, 100000, 'Health', 'Tamil Nadu'),
(102, 0, 100000, 'Health', 'Tamil Nadu'),
(103, 5, 99999999, 'Health', 'Tamil Nadu'),
(104, 60, 99999999, 'Health', 'Tamil Nadu'),
(105, 18, 99999999, 'Health', 'Tamil Nadu'),
(106, 18, 99999999, 'Health', 'Tamil Nadu'),
(107, 0, 99999999, 'Health', 'Tamil Nadu'),
(108, 18, 99999999, 'Health', 'Tamil Nadu'),
(109, 0, 99999999, 'Health', 'Tamil Nadu'),
(110, 18, 99999999, 'Health', 'Tamil Nadu'),

-- Housing & Employment (111-140)
(111, 18, 100000, 'Housing', 'Tamil Nadu'),
(112, 18, 300000, 'Housing', 'Tamil Nadu'),
(113, 18, 120000, 'Housing', 'Tamil Nadu'),
(114, 18, 100000, 'Housing', 'Tamil Nadu'),
(115, 18, 100000, 'Housing', 'Tamil Nadu'),
(116, 21, 600000, 'Housing', 'Tamil Nadu'),
(117, 21, 600000, 'Housing', 'Tamil Nadu'),
(118, 18, 200000, 'Housing', 'Tamil Nadu'),
(119, 18, 300000, 'Housing', 'Tamil Nadu'),
(120, 18, 99999999, 'Housing', 'Tamil Nadu'),
(121, 18, 99999999, 'Employment', 'Tamil Nadu'),
(122, 18, 99999999, 'Employment', 'Tamil Nadu'),
(123, 18, 150000, 'Employment', 'Tamil Nadu'),
(124, 21, 5000000, 'Employment', 'Tamil Nadu'),
(125, 18, 99999999, 'Employment', 'Tamil Nadu'),
(126, 18, 99999999, 'Employment', 'Tamil Nadu'),
(127, 18, 99999999, 'Employment', 'Tamil Nadu'),
(128, 18, 99999999, 'Employment', 'Tamil Nadu'),
(129, 18, 99999999, 'Employment', 'Tamil Nadu'),
(130, 18, 99999999, 'Employment', 'Tamil Nadu'),
(131, 18, 99999999, 'Employment', 'Tamil Nadu'),
(132, 18, 99999999, 'Employment', 'Tamil Nadu'),
(133, 18, 200000, 'Employment', 'Tamil Nadu'),
(134, 18, 99999999, 'Employment', 'Tamil Nadu'),
(135, 18, 99999999, 'Employment', 'Tamil Nadu'),
(136, 18, 99999999, 'Employment', 'Tamil Nadu'),
(137, 18, 99999999, 'Employment', 'Tamil Nadu'),
(138, 18, 99999999, 'Employment', 'Tamil Nadu'),
(139, 18, 99999999, 'Employment', 'Tamil Nadu'),
(140, 18, 100000, 'Employment', 'Tamil Nadu'),

-- General (141-150)
(141, 18, 99999999, 'General', 'Tamil Nadu'),
(142, 18, 99999999, 'General', 'Tamil Nadu'),
(143, 0, 99999999, 'General', 'Tamil Nadu'),
(144, 0, 99999999, 'General', 'Tamil Nadu'),
(145, 0, 99999999, 'General', 'Tamil Nadu'),
(146, 0, 99999999, 'General', 'Tamil Nadu'),
(147, 0, 99999999, 'General', 'Tamil Nadu'),
(148, 0, 99999999, 'General', 'Tamil Nadu'),
(149, 0, 99999999, 'General', 'Tamil Nadu'),
(150, 0, 99999999, 'General', 'Tamil Nadu');

-- Sync sequences after manual ID insertion
SELECT setval(pg_get_serial_sequence('schemes', 'id'), coalesce(max(id), 0) + 1, false) FROM schemes;
SELECT setval(pg_get_serial_sequence('eligibility_rules', 'id'), coalesce(max(id), 0) + 1, false) FROM eligibility_rules;
